apiVersion: 1

datasources:
  - name: influxdb-auto
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: Optimaaxx
      defaultBucket: Data-IoT
    secureJsonData:
      token: supersecrettoken123
